language: python
python:
  - 2.7
  - 3.7
 
os:
    - linux
    - osx 

osx_image: xcode10.1
  
virtualenv:
  system_site_packages: false
  
# command to run tests
script:
  - python2 tests.py
  - python3 tests.py

install:  
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install python; fi

